baseURL = "https://blog.enjoythejourney.xyz/"
languageCode = "en-us"
title = "Enjoy the journey"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  author = "Jordan Bae"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowToc = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"
  disableThemeToggle = false

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/jordan-bae-251042136/"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  identifier = "projects"
  name = "프로젝트"
  url = "/projects/"
  weight = 2

[[menu.main]]
  identifier = "startup"
  name = "스타트업"
  url = "/startup/"
  weight = 3

[[menu.main]]
  identifier = "tech"
  name = "기술"
  url = "/tech/"
  weight = 4

[[menu.main]]
  identifier = "life"
  name = "일상"
  url = "/life/"
  weight = 5

